name: Latest Build

on:
  push:
    branches:
      - '*'
      - '!development_old_nwjs'
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        nwjs: ['0.44.5', '0.82.0']

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: yarn version
        run: |
          yarn version

      - name: node version
        run: |
          node --version

      - uses: kanga333/variable-mapper@master
        with:
          key: "${{ matrix.os }}"
          map: |
            {
              "ubuntu-latest": { "platform": "linux" },
              "macOS-latest": { "platform": "osx" },
              "windows-latest": { "platform": "win" }
            }

      - name: Build info macOS
        if: matrix.os == 'macOS-latest'
        run: |
          echo Build ${{ env.platform }}64 on nw-v${{ matrix.nwjs }}

      - name: Build info Linux & Windows
        if: matrix.os != 'macOS-latest'
        run: |
          echo Build ${{ env.platform }}32 on nw-v${{ matrix.nwjs }}
          echo Build ${{ env.platform }}64 on nw-v${{ matrix.nwjs }}

      - name: Build macOS
        if: matrix.os == 'macOS-latest'
        run: |
          yarn
          yarn gulp dist --platforms=${{ env.platform }}64 --nwVersion=${{ matrix.nwjs }}

      - name: Build Linux & Windows
        if: matrix.os != 'macOS-latest'
        run: |
          yarn
          yarn gulp dist --platforms=${{ env.platform }}32 --nwVersion=${{ matrix.nwjs }}
          yarn gulp dist --platforms=${{ env.platform }}64 --nwVersion=${{ matrix.nwjs }}

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.platform }}-${{ matrix.nwjs }}
          path: build

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Context
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          allowUpdates: true
          name: ${{ github.ref_name }}
          artifacts: "artifacts/*"
